import { ArchitectureFlow } from './components/ArchitectureFlow'

const stages = [
  ['01 · Identity and request', [['Demo sign-in', 'Server session owns customer identity'], ['Conversation scope', 'Owned chat · recent turns + references'], ['Deterministic precheck', 'Normalize · lengths · keyword signals'], ['Jev intent + threshold', 'Uncertain information/action → reads only; no proposals']]],
  ['Task continuation', [['Routing precheck', 'Explicit task · topic signals · bounded candidates'], ['Jev when ambiguous', 'New · resume · correct · abandon · clarify'], ['Application gate', 'Owned task · confidence ≥ 0.8 · margin ≥ 0.1']]],
  ['02 · Bounded support agent', [['Call prechecks', 'Per-run limits · cumulative task limits'], ['Typed model decision', 'Tagged branch · one schema repair'], ['Scoped tools', 'Validated arguments · owned orders'], ['Verified observations', 'Evidence IDs · exact source locators']]],
  ['03 · Three sources of authority', [['Policy index', 'Explicit ingestion · lexical + vector fusion'], ['Current order state', 'Database records · version · eligibility'], ['Catalog and cases', 'Fixture products · owned saved cases']]],
  ['04 · Verify output', [['Deterministic checks', 'Evidence · ownership · address/statement'], ['Jev support + threshold', 'Semantic grounding · one answer repair'], ['Application decision', 'Answer · pending proposal · review case']]],
  ['05 · Explicit action boundary', [['Customer confirms', 'Specific saved proposal · confirm/reject'], ['Fresh execution checks', 'Ownership · state · version · policy'], ['Atomic mock change', 'Conditional update · unique receipt']]],
  ['06 · Save and pause or finish', [['Shared llm_runs', 'One execution segment · usage · stop reason'], ['Task checkpoint', 'Goal · target · pending decision · version'], ['Follow-ups', 'Validate saved policy · refresh mutable facts']]],
] as const
export default function SupportSystemDiagram() {
  return <div className="knowledge-architecture" role="region" aria-label="Customer Support architecture">
    <p className="architecture-modal-note">Exact order-list requests take a deterministic route: validate → read owned current orders → render a checked list → save. They do not call a model. Other requests use the bounded flow below.</p>
    <p className="architecture-modal-note">Policy passages explain retailer rules. Current order records determine account facts. The model proposes; application checks and explicit confirmation govern changes.</p>
    <p className="architecture-modal-note">Cancellation, address changes and human-review requests persist task state between messages. New topics preserve pending tasks. Explicit replies route directly; ambiguous references use Jev with bounded task context. Corrections re-resolve the target. Pending proposals still require their specific approval or rejection card. Policy reuse requires the same task and exact current passage, revision and effective date; grounding still checks relevance. Task limits accumulate across messages: 12 executions, 60,000 reported tokens and 24 tool requests. Corrections discard saved policy; confirmation still rechecks current state and remains available if model budgets are exhausted. No process stays running while waiting.</p>
    {stages.map(([label, nodes]) => <section className="knowledge-architecture-stage" key={label}><h3>{label}</h3><ArchitectureFlow nodes={nodes} connected={label !== '03 · Three sources of authority'} />{label === '02 · Bounded support agent' && <p className="knowledge-architecture-footnote">Tool observations return to the agent for its next bounded decision. Completed repeated reads close source selection; a terminal schema excludes further tools. Answer, clarification, or proposal exits the loop. Each decision permits one bounded schema repair; failed attempts retain usage and diagnostics. Eight model turns, six tool calls, 20,000 reported tokens, and a 120-second deadline.</p>}{label === '05 · Explicit action boundary' && <div className="knowledge-architecture-split"><div><strong>Order change branch</strong><small>Confirmation rechecks current state. A successful change saves a unique receipt; a rejected proposal leaves the order unchanged.</small></div><div><strong>Human-review branch → saved pending case</strong><small>Refund/return/warranty/damage requests bypass automatic execution. Ineligible or stale changes also route here.</small></div></div>}{label === '05 · Explicit action boundary' && <p className="knowledge-architecture-footnote">Cancellation/address change applies only to paid, unfulfilled orders. Refund, return, warranty, damage, stale/blocked actions, or escalation route to human review. These are alternative branches; no refund executor exists. Technical failures save diagnostics and do not automatically create tickets.</p>}</section>)}
    <p className="knowledge-architecture-footnote">Customers and orders are synthetic; sign-in is simulated. Policy embeddings are explicitly ingested and mock vectors demonstrate wiring only. No payment, carrier, or external ticket writes. The walkthrough records visible decisions; private model reasoning is unavailable.</p>
  </div>
}
